name: aplikacija2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

platforms: android ios

dependencies:
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  lottie: ^2.6.0
  pinput: ^2.2.31
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/picture1.jpg
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
